"use client"
import { Nunito } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar";
import { LangProvider } from "@/contexts/langContext";
import { useParams } from "next/navigation";

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const params = useParams()
  const { slug } = params

  return (
    <html lang="en">
      <body className={`${nunito.variable} antialiased`}>
        <LangProvider slug={slug}>
          <Navbar />
          {children}
        </LangProvider>
      </body>
    </html>
  );
}
